{{-- resources/views/partials/country-codes.blade.php --}}
@foreach([
    '+91' => 'India',
    '+1' => 'United States / Canada',
    '+44' => 'United Kingdom',
    '+971' => 'United Arab Emirates',
    '+966' => 'Saudi Arabia',
    '+33' => 'France',
    '+49' => 'Germany',
    '+81' => 'Japan',
    '+86' => 'China',
    '+7' => 'Russia',
    '+55' => 'Brazil',
    '+61' => 'Australia',
    '+39' => 'Italy',
    '+34' => 'Spain',
    '+41' => 'Switzerland',
    '+92' => 'Pakistan',
    '+880' => 'Bangladesh',
    '+94' => 'Sri Lanka',
    '+977' => 'Nepal',
    '+60' => 'Malaysia',
    '+62' => 'Indonesia',
    '+63' => 'Philippines',
    '+82' => 'South Korea',
    '+90' => 'Turkey',
    '+27' => 'South Africa',
    '+234' => 'Nigeria',
    '+20' => 'Egypt',
    '+31' => 'Netherlands',
    '+46' => 'Sweden',
    '+47' => 'Norway',
    '+358' => 'Finland',
    '+32' => 'Belgium',
    '+43' => 'Austria',
    '+353' => 'Ireland',
    '+64' => 'New Zealand',
    '+65' => 'Singapore',
    '+965' => 'Kuwait',
    '+968' => 'Oman',
    '+974' => 'Qatar',
    '+962' => 'Jordan',
] as $code => $country)
    <option value="{{ $code }}" @selected(old($inputName, $selected ?? '') == $code)>
        {{ $code }} ({{ $country }})
    </option>
@endforeach